name: 'Increment major'
on:
  push:
    branches:
      - main
jobs:
  latest-version:
    runs-on: ubuntu-latest
    steps:
      - uses: slime-hatena/semantic-versioning-calculator-action@main
        id: calc
        with:
          version: '1.2.3+develop'
          increment_major: 'true'
      - run: echo "${{steps.calc.outputs.version}}" # 2.0.0
