name: 'Increment patch'
on:
  push:
    branches:
      - main
test:
  runs-on: ubuntu-latest
  steps:
    - uses: slime-hatena/semantic-versioning-calculator-action@main
      id: calc
      with:
        version: '1.2.3+develop'
        increment_patch: 'true'
    - run: echo "${{steps.calc.outputs.version}}" # 1.2.4
